export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_USER = 'ADD_USER';
export const GET_USER = 'GET_USER';

export const GET_COURSES = 'GET_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const GET_COURSE = 'GET_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const GET_FACULTY = 'GET_FACULTY';
export const ADD_FACULTY = 'ADD_FACULTY';
export const GET_FACULTYS = 'GET_FACULTYS';
export const UPDATE_FACULTY = 'UPDATE_FACULTY';
export const UPDATE_FACULTY_COURSE = 'UPDATE_FACULTY_COURSE';
export const DELETE_FACULTY = 'DELETE_FACULTY';

export const GET_PLAYLIST = 'GET_PLAYLIST';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';

export const GET_STUDENTS = 'GET_STUDENTS';

export const GET_ASCOURSES = 'GET_ASCOURSES';
export const GET_ASCOURSE = 'GET_ASCOURSE';
export const DELETE_ASCOURSE = 'DELETE_ASCOURSE';

export const DELETE_TIME = 'DELETE_TIME';
export const ADD_TIME = 'ADD_TIME';
export const GET_TIME = 'GET_TIME';
export const GET_TIMES = 'GET_TIMES';
export const UPDATE_TIME = 'UPDATE_TIME';

export const DELETE_STUDIO = 'DELETE_STUDIO';
export const ADD_STUDIO = 'ADD_STUDIO';
export const GET_STUDIO = 'GET_STUDIO';
export const GET_STUDIOS = 'GET_STUDIOS';
export const UPDATE_STUDIO = 'UPDATE_STUDIO';

export const GET_FEATURE = 'GET_FEATURE';
export const ADD_FEATURE = 'ADD_FEATURE';
export const GET_FEATURES = 'GET_FEATURES';
export const UPDATE_FEATURE = ' UPDATE_FEATURE';
export const DELETE_FEATURE = ' DELETE_FEATURE';

export const GET_LECTURE = ' GET_LECTURE';
export const ADD_LECTURE = 'ADD_LECTURE';
export const GET_LECTURES = 'GET_LECTURES';
export const UPDATE_LECTURE = ' UPDATE_LECTURE';
export const DELETE_LECTURE = 'DELETE_LECTURE';

export const GET_MAINCOURSE = 'GET_MAINCOURSE';
export const ADD_MAINCOURSE = ' ADD_MAINCOURSE';
export const GET_MAINCOURSES = ' GET_MAINCOURSES';
export const UPDATE_MAINCOURSE = 'UPDATE_MAINCOURSE';
export const DELETE_MAINCOURSE = 'DELETE_MAINCOURSE';

export const GET_COURSELEVEL = ' GET_COURSELEVEL';
export const ADD_COURSELEVEL = ' ADD_COURSELEVEL';
export const GET_COURSELEVELS = ' GET_COURSELEVELS';
export const UPDATE_COURSELEVEL = '  UPDATE_COURSELEVEL';
export const DELETE_COURSELEVEL = '  DELETE_COURSELEVEL';

export const DELETE_CHAPTER = ' DELETE_CHAPTER';
export const UPDATE_CHAPTER = '  UPDATE_CHAPTER';
export const GET_CHAPTERS = '   GET_CHAPTERS';
export const ADD_CHAPTER = ' ADD_CHAPTER';
export const GET_CHAPTER = ' GET_CHAPTER';

export const ADD_LECTURECOURSE = 'ADD_LECTURECOURSE';
export const GET_LECTURESCOURSE = 'GET_LECTURESCOURSE';
export const DELETE_LECTURECOURSE = 'DELETE_LECTURESCOURSE';
export const UPDATE_LECTURECOURSE = 'UPDATE_LECTURESCOURSE';

export const GET_DEMOPACKAGE = 'GET_DEMOPACKAGE';
export const ADD_DEMOPACKAGE = 'ADD_DEMOPACKAGE';
export const GET_DEMOPACKAGES = 'GET_DEMOPACKAGES';
export const UPDATE_DEMOPACKAGE = 'UPDATE_DEMOPACKAGE';
export const DELETE_DEMOPACKAGE = 'DELETE_DEMOPACKAGE';

export const GET_CREDIT = 'GET_CREDIT';
export const ADD_CREDIT = 'ADD_CREDIT';
export const GET_CREDITS = 'GET_CREDITS';
export const UPDATE_CREDIT = 'UPDATE_CREDIT';
export const DELETE_CREDIT = 'DELETE_CREDIT';

export const DELETE_PROJECT = ' DELETE_PROJECT';
export const UPDATE_PROJECT = '  UPDATE_PROJECT';
export const GET_PROJECTS = '   GET_PROJECTS';
export const ADD_PROJECT = ' ADD_PROJECT';
export const GET_PROJECT = ' GET_PROJECT';

export const DELETE_PACKAGE = ' DELETE_PACKAGE';
export const UPDATE_PACKAGE = '  UPDATE_PACKAGE';
export const GET_PACKAGES = '   GET_PACKAGES';
export const ADD_PACKAGE = ' ADD_PACKAGE';
export const GET_PACKAGE = ' GET_PACKAGE';

export const DELETE_TOPUP = ' DELETE_TOPUP';
export const UPDATE_TOPUP = '  UPDATE_TOPUP';
export const GET_TOPUPS = '   GET_TOPUPS';
export const ADD_TOPUP = ' ADD_TOPUP';
export const GET_TOPUP = ' GET_TOPUP';

export const UPDATE_OFFLINEUSER = ' UPDATE_OFFLINEUSER';
export const DELETE_OFFLINEUSER = '  DELETE_OFFLINEUSER';
export const GET_OFFLINEUSERS = '   GET_OFFLINEUSERS';
export const ADD_OFFLINEUSER = 'ADD_OFFLINEUSER';
export const GET_OFFLINEUSER = 'GET_OFFLINEUSER';

export const UPDATE_OFFLINEOFFER = ' UPDATE_OFFLINEOFFER';
export const DELETE_OFFLINEOFFER = '  DELETE_OFFLINEUSER';
export const GET_OFFLINEOFFERS = '   GET_OFFLINEOFFERS';
export const ADD_OFFLINEOFFER = 'ADD_OFFLINEOFFER';
export const GET_OFFLINEOFFER = 'GET_OFFLINEOFFER';

export const GET_REFUND = 'GET_REFUND';
export const ADD_REFUND = 'ADD_REFUND';
export const GET_REFUNDS = 'GET_REFUNDS';
export const UPDATE_REFUND = 'UPDATE_REFUND';
export const DELETE_REFUND = 'DELETE_REFUND';
